# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotifake', '0002_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=200)),
            ],
        ),
    ]
