# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotifake', '0004_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='link',
            new_name='image_link',
        ),
    ]
