# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spotifake', '0005_auto_20180117_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_entertainers',
            field=models.ManyToManyField(to='Spotifake.Entertainer'),
        ),
        migrations.AddField(
            model_name='album',
            name='album_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Spotifake.Images'),
        ),
        migrations.AddField(
            model_name='entertainer',
            name='entertainer_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Spotifake.Images'),
        ),
        migrations.AddField(
            model_name='music',
            name='music_album',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Spotifake.Album'),
        ),
    ]
